services:
  - type: web
    name: universal-db-explorer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    scaling:
      minInstances: 1
      maxInstances: 1